---
- name: Test SSH connection and display hostname
  hosts: oracle_servers
  become: yes

  tasks:
    - name: Ping the hosts to verify connectivity
      ansible.builtin.ping:

    - name: Run hostname command and display output
      ansible.builtin.command:
        cmd: hostname
      register: hostname_output

    - name: Display hostname for {{ inventory_hostname }}
      ansible.builtin.debug:
        msg: "Hostname of {{ inventory_hostname }}: {{ hostname_output.stdout }}"
